---
title: "Gov 50 Final Project"
author: Gregor Kossmann
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts (Milestone 1)

For my Gov 50 final project I am interested in exploring the effect that the Marshall Plan has had on European Recovery following the second world war. I am generally very interested in the impact of US foreign aid on recipient countries (whether that be political, economic, or diplomatic), and the Marshall Plan is one of the biggest examples of such aid (with hopefully the most data). I think economic factors might have the most data, so I will look at GDP levels, spending levels, and other more precise metrics that may inform a relationship (in addition to various other diplomatic and political interactions that might be telling). Following that, I suppose I will have to conduct a straightforward regression analysis (although I do not know yet how to do that in R), between foreign aid and economic outcomes. 

## Proposal (Milestone 2)

My interest in the Marshall plan has narrowed down more specifically to investigating the economic impact of the Marshall Plan on Europe, which I will attempt to do by analyzing a variety of economic measures found on Statista and CESSDA. Although not finalized, my research question will center around the study of various economic indicators (industrial production, agricultural production, distribution of aid and loans, and GDP growth) as they relate to the Marshall Plan, questioning to what extent did the plan improve Europe's economic outlook and truly serve as a model for reconstruction and development. Standard economic theory would suggest that given the massive influx of aid and capital that entered an already barren and deprived landscape in Europe, the Marshall Plan provided much needed stimulus to reinvigorate the economy, and the patterns in the data would confirm this upward trajectory of income (GDP) and production. If, however, the patterns in the data show that the early years following the implementation of the Marshall Plan saw relatively meager growth, it is more likely that economic improvements in future decades (60's, 70's), were more the result of factors other than the Marshall Plan. I will quantify the Marshall Plan through exact figures on foreign aid disbursements and loans given out between 1948-1952, with my outcome variables consisting of various economic indicators that combined can paint the overall macroeconomic standing of these European countries following the introduction of the Marshall Plan. Specifically, the datasets I have found include, among others, the OECD Employment and Labor Market Statistics from 1950 onwards, Post-WWII industrial (and agricultural) production in Western European countries between 1947 and 1951, and average annual GDP growth in European countries during the cold war (1950-1959).   


